name: Docker Image CI test

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: App Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test
        run: |
          python test_sample.py
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and release to DockerHub
        env:  # 환경변수로 값을 지정하여 사용할 수 있습니다.
          REPO: jyko94
          LAYER_NAME: test
        run: |
          docker build -t $LAYER_NAME  .
          docker tag $LAYER_NAME:latest $REPO/$LAYER_NAME:latest
          docker push $REPO/$LAYER_NAME:latest
